### ISSUE TITLE
No se ven las imágenes del artículo: "Las mejores 5 tipografías para programar"

### ISSUE THREAD

**Issue by Jonatandb** [midudev/midu.dev#34]
Hola Miguel, espero que estés muy bien 😀👌

Te quería avisar que faltó subir la carpeta "galleries", por lo que no se ven las imágenes [en el artículo](https://midu.dev/las-mejores-tipografias-para-programar/):

![image](https://user-images.githubusercontent.com/8082172/88414384-244baa00-cdb3-11ea-8def-201015f6649c.png)

Un abrazo y gracias por compartir siempre tanto conocimiento de calidad 🤓🙏🏻

**Comment by midudev** [comment]
Arreglado! Gracias por avisar!
