### ISSUE TITLE
¿Qué ventajas trae usar hugo-bin sobre HUGO?

### ISSUE THREAD

**Issue by ferdinandalexa** [midudev/midu.dev#36]
Estoy empezando mi blog personal. Estuve buscando SSG que trabajaran `.md`  y HUGO me convenció. 
Uso la documentación oficial y tu blog como ejemplo. Vi que en tu package.json usas hugo-bin como wrapper para HUGO en node. 

Supongo que es para no tener que instalar HUGO, asegurar que pueda correr en cualquier entorno y y no realizar la configuración manualmente. Pero **¿trae alguna ventaja usarlo de dicha forma?**.

**Comment by midudev** [comment]
La ventaja principal es la simplificación del paso de instalación de las dependencias y uso de la misma en CI. Al final es un wrapper del mismo ejecutable, pero como uso Vercel, me simplifica mucho la instalación. Además así tengo todas las dependencias instaladas en el mismo proceso.

**Comment by ferdinandalexa** [comment]
Gracias por la respuesta. Haré mis pruebas y veré cuál me viene mejor.

¡De nuevo, gracias! 🍍 🍍 🍍
